### ISSUE TITLE
Move TODO to Wiki

### ISSUE THREAD

**Issue by inodaf** [inodaf/ts-node-starter#2]
Write the features bellow in the repository's Wiki:

- [x] TypeScript Support
	- [x] Development
	- [x] Build Dev & Prod
	- [x] Paths
	- [x] VSCode Debugging
- [x] Env Vars
	- [x] Production
	- [x] Staging
	- [x] Development
- [x] Test Support - AVA
	- [x] TS Support
	- [x] Resolve TS Paths
	- [x] Coverage Reports
	- [x] Env Vars Support
	- [x] MSW
- [x] Lint - TypeScript ESLint
- [x] Format - Prettier
- [x] CI
